/**
 * Minimal, safe Markdown renderer for coach replies.
 *
 * The coach's output is generated by our own backend (Gemini or the local nutrition
 * engine), but it is still untrusted text, so this renders a fixed subset into React
 * elements rather than injecting HTML. Supported: headings, bullet and numbered lists,
 * bold, italics, inline code, and paragraphs.
 */

const INLINE_TOKENS = /(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/g;

const renderInline = (text, keyPrefix) => {
  const parts = String(text).split(INLINE_TOKENS).filter((p) => p !== '');

  return parts.map((part, i) => {
    const key = `${keyPrefix}-${i}`;

    if (part.startsWith('**') && part.endsWith('**') && part.length > 4) {
      return <strong key={key}>{part.slice(2, -2)}</strong>;
    }
    if (part.startsWith('*') && part.endsWith('*') && part.length > 2) {
      return <em key={key}>{part.slice(1, -1)}</em>;
    }
    if (part.startsWith('`') && part.endsWith('`') && part.length > 2) {
      return (
        <code key={key} style={CODE_STYLE}>
          {part.slice(1, -1)}
        </code>
      );
    }
    return <span key={key}>{part}</span>;
  });
};

const CODE_STYLE = {
  background: 'rgba(255,255,255,0.08)',
  padding: '0.1rem 0.35rem',
  borderRadius: '5px',
  fontSize: '0.86em',
  fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace'
};

const renderBlock = (block, index) => {
  const key = `md-${index}`;

  if (block.type === 'heading') {
    const size = block.level === 3 ? '1rem' : '1.1rem';
    return (
      <div
        key={key}
        style={{
          fontSize: size,
          fontWeight: 700,
          color: 'var(--accent-green)',
          margin: '0.25rem 0 0.5rem',
          letterSpacing: '0.01em'
        }}
      >
        {renderInline(block.text, key)}
      </div>
    );
  }

  if (block.type === 'list') {
    const isOrdered = block.ordered;
    return (
      <ul
        key={key}
        style={{
          listStyle: 'none',
          margin: '0.4rem 0',
          padding: 0,
          display: 'flex',
          flexDirection: 'column',
          gap: '0.35rem'
        }}
      >
        {block.items.map((item, i) => (
          <li key={`${key}-${i}`} style={{ display: 'flex', gap: '0.55rem', alignItems: 'flex-start' }}>
            <span
              style={{
                color: 'var(--accent-green)',
                fontWeight: 700,
                fontSize: '0.85em',
                lineHeight: 1.6,
                minWidth: isOrdered ? '1.2rem' : '0.6rem',
                textAlign: isOrdered ? 'right' : 'left'
              }}
            >
              {isOrdered ? `${i + 1}.` : '•'}
            </span>
            <span style={{ flex: 1 }}>{renderInline(item, `${key}-${i}`)}</span>
          </li>
        ))}
      </ul>
    );
  }

  return (
    <p key={key} style={{ margin: '0.4rem 0' }}>
      {renderInline(block.text, key)}
    </p>
  );
};

/** Split raw markdown into blocks: headings, lists, paragraphs. */
const parseBlocks = (source) => {
  const lines = String(source || '').split('\n');
  const blocks = [];
  let paragraph = [];

  const flushParagraph = () => {
    if (paragraph.length) {
      blocks.push({ type: 'paragraph', text: paragraph.join(' ').trim() });
      paragraph = [];
    }
  };

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      flushParagraph();
      continue;
    }

    const headingMatch = trimmed.match(/^(#{1,6})\s+(.*)$/);
    if (headingMatch) {
      flushParagraph();
      blocks.push({
        type: 'heading',
        level: headingMatch[1].length,
        text: headingMatch[2].replace(/\*\*/g, '')
      });
      continue;
    }

    const bulletMatch = trimmed.match(/^[-*•]\s+(.*)$/);
    const orderedMatch = trimmed.match(/^(\d+)[.)]\s+(.*)$/);

    if (bulletMatch || orderedMatch) {
      flushParagraph();
      const ordered = Boolean(orderedMatch);
      const items = [];

      // Consume every consecutive list line
      while (i < lines.length) {
        const current = lines[i].trim();
        const bullet = current.match(/^[-*•]\s+(.*)$/);
        const numbered = current.match(/^(\d+)[.)]\s+(.*)$/);

        if (bullet) {
          items.push(bullet[1]);
        } else if (numbered) {
          items.push(numbered[2]);
        } else if (current && items.length && !/^#{1,6}\s/.test(current) && !/^[-*•\d]/.test(current)) {
          // Wrapped continuation of the previous item
          items[items.length - 1] += ` ${current}`;
        } else {
          break;
        }
        i += 1;
      }
      i -= 1;

      blocks.push({ type: 'list', ordered, items });
      continue;
    }

    paragraph.push(trimmed);
  }

  flushParagraph();
  return blocks;
};

export default function Markdown({ children }) {
  const content = String(children || '').trim();

  if (!content) {
    return <span style={{ color: 'var(--text-muted)', fontStyle: 'italic' }}>No response returned.</span>;
  }

  const blocks = parseBlocks(content);

  return <div style={{ display: 'flex', flexDirection: 'column' }}>{blocks.map(renderBlock)}</div>;
}